#!/usr/bin/env bash
# Generate the Pi keeper's environment file (ZER-16) from the deployment
# manifest. Runs ON the Pi: deploy-pi.sh calls it after every deploy or resume,
# before it starts zeracle-keeper.timer.
#
# Why generated: ZRCL_ADDRESS is an L2 address and changes on every fresh
# chain, so a hand-written /etc/zeracle/keeper.env would silently point the
# keeper at a dead token after the next redeploy — the same trap
# ops/gen-chain-server-env.sh closes for chain-server.
#
# The key is anvil #4, the keeper key run-keeper.sh's header documents for the
# sandbox (never #0, the sequencer's; never #1-#3, the deployer, guardian and
# governance keys). It is anvil's public dev key, so the file holds no secret on
# this host — it is still written 0600 because the same file on a testnet ops
# host would.
#
# Usage: gen-keeper-env.sh <deployment-manifest.json> [output-env-file] [owner]
set -euo pipefail

MANIFEST=${1:?usage: gen-keeper-env.sh <deployment-manifest.json> [output] [owner]}
OUT=${2:-/etc/zeracle/keeper.env}
# The unit runs as admin (lib/keeper/zeracle-keeper.service); systemd reads the
# EnvironmentFile as root, but an operator reading it by hand should not need to.
OWNER=${3:-admin}

KEEPER_KEY_ANVIL_4=0x47e179ec197488593b187f80a00eb0da91f1b9d0b13f8733639f19c30a34926a

# Measured 2026-09-25 on the Pi (Aztec 5.2.0): the node still served the
# L2->L1 membership witness for a message 14.7 h / 735 blocks old. 5.2.0 builds
# the witness from the archiver's blocks plus the L1 Outbox roots
# (archiver/dest/modules/outbox_trees_resolver.js), not from pruned world
# state, so there is no ~2 h proof window here and a failed claim can simply be
# retried on the next run. Hence:
#   - PENDING_FLUSH_MAX_AGE_SECS 30 days, not run-keeper.sh's 7200: expiring
#     at 2 h would drop hashes that are still claimable. It is not unbounded
#     because a fresh chain makes every old hash meaningless — deploy-pi.sh
#     also clears pending-flush on a fresh chain.
#   - KEEPER_CLAIM_WAIT_SECS 1800, not 5400: the Pi proves each block as it
#     lands (proven == tip), so a witness normally appears within a block or
#     two; a longer in-run wait only holds the lock for a claim that is better
#     retried tomorrow.
PENDING_FLUSH_MAX_AGE_SECS=2592000
KEEPER_CLAIM_WAIT_SECS=1800

[ -f "$MANIFEST" ] || { echo "FATAL: manifest not found: $MANIFEST" >&2; exit 1; }

# `// empty` so a missing key trips the validation instead of writing "null".
ZRCL=$(jq -r '.l2.contracts.zeracleToken // empty' "$MANIFEST")
if ! [[ "$ZRCL" =~ ^0x[0-9a-fA-F]{64}$ ]]; then
  echo "FATAL: .l2.contracts.zeracleToken in $MANIFEST is not an L2 address: '${ZRCL}'" >&2
  echo "       Without it the keeper's sweep and flush fall into FIXTURE mode." >&2
  exit 1
fi

REPO=${REPO:-/opt/zeracle}
mkdir -p "$(dirname "$OUT")"
# Written to a temp file and moved, so a failure never leaves a half-written env
# for the next timer run to read. umask first: the key must never be readable,
# not even for the instant between write and chmod.
tmp="$(umask 077 && mktemp "$OUT.XXXXXX")"
cat > "$tmp" <<EOF
# GENERATED by deployments/pi/gen-keeper-env.sh — do not edit.
# Source: $MANIFEST (generatedAt $(jq -r '.generatedAt // "unknown"' "$MANIFEST"))
KEEPER_L1_PRIVATE_KEY=$KEEPER_KEY_ANVIL_4
V1_L2_DIR=$REPO/v1-l2
ZRCL_ADDRESS=$ZRCL
KEEPER_STATE_DIR=/var/lib/zeracle-keeper
KEEPER_CLAIM_WAIT_SECS=$KEEPER_CLAIM_WAIT_SECS
PENDING_FLUSH_MAX_AGE_SECS=$PENDING_FLUSH_MAX_AGE_SECS
EOF
chmod 600 "$tmp"
if [ "$(id -u)" -eq 0 ]; then chown "$OWNER:$OWNER" "$tmp"; fi
mv -f "$tmp" "$OUT"
# Never echo the key.
echo "Wrote $OUT (ZRCL_ADDRESS=$ZRCL)"
