#!/usr/bin/env bash
# Generate the Pi keeper's environment file (ZER-16) from the deployment
# manifest. Runs ON the Pi: deploy-pi.sh calls it after every deploy or resume,
# before it starts zeracle-keeper.timer.
#
# Why generated: ZRCL_ADDRESS is an L2 address and changes on every fresh
# chain, so a hand-written /etc/zeracle/keeper.env would silently point the
# keeper at a dead token after the next redeploy — the same trap
# ops/gen-chain-server-env.sh closes for chain-server.
#
# The key is anvil #4, the keeper key run-keeper.sh's header documents for the
# sandbox (never #0, the sequencer's; never #1-#3, the deployer, guardian and
# governance keys). It is anvil's public dev key, so the file holds no secret on
# this host — it is still written 0600 because the same file on a testnet ops
# host would.
#
# Usage: gen-keeper-env.sh <deployment-manifest.json> [output-env-file] [owner]
set -euo pipefail

MANIFEST=${1:?usage: gen-keeper-env.sh <deployment-manifest.json> [output] [owner]}
OUT=${2:-/etc/zeracle/keeper.env}
# The unit runs as admin (lib/keeper/zeracle-keeper.service); systemd reads the
# EnvironmentFile as root, but an operator reading it by hand should not need to.
OWNER=${3:-admin}

KEEPER_KEY_ANVIL_4=0x47e179ec197488593b187f80a00eb0da91f1b9d0b13f8733639f19c30a34926a

# Measured 2026-09-25 on the Pi (Aztec 5.2.0): the node still served the
# L2->L1 membership witness for a message 14.7 h / 735 blocks old. 5.2.0 builds
# the witness from the archiver's blocks plus the L1 Outbox roots
# (archiver/dest/modules/outbox_trees_resolver.js), not from pruned world
# state, so there is no ~2 h proof window here and a failed claim can simply be
# retried on the next run. Hence:
#   - PENDING_FLUSH_MAX_AGE_SECS 30 days, not run-keeper.sh's 7200: expiring
#     at 2 h would drop hashes that are still claimable. It is not unbounded
#     because a fresh chain makes every old hash meaningless — deploy-pi.sh
#     also clears pending-flush on a fresh chain.
#   - KEEPER_CLAIM_WAIT_SECS 1800, not 5400: the Pi proves each block as it
#     lands (proven == tip), so a witness normally appears within a block or
#     two; a longer in-run wait only holds the lock for a claim that is better
#     retried tomorrow.
PENDING_FLUSH_MAX_AGE_SECS=2592000
KEEPER_CLAIM_WAIT_SECS=1800

[ -f "$MANIFEST" ] || { echo "FATAL: manifest not found: $MANIFEST" >&2; exit 1; }

# `// empty` so a missing key trips the validation instead of writing "null".
ZRCL=$(jq -r '.l2.contracts.zeracleToken // empty' "$MANIFEST")
if ! [[ "$ZRCL" =~ ^0x[0-9a-fA-F]{64}$ ]]; then
  echo "FATAL: .l2.contracts.zeracleToken in $MANIFEST is not an L2 address: '${ZRCL}'" >&2
  echo "       Without it the keeper's sweep and flush fall into FIXTURE mode." >&2
  exit 1
fi

# Every address the keeper would otherwise read from the repo's deployment
# files is pinned from the manifest too. Those files are NOT a safe source on
# the Pi: `make sync-pi` ships the laptop's v1-l1/deployments/{local,bridge}.json
# over the Pi's, and the laptop copies describe whatever chain the laptop last
# saw. Measured 2026-09-25: after a sync, the first keeper run converted and
# cushioned against a LiquidityPool address with no code on the Pi's anvil.
# The manifest is written by the deploy itself and nothing syncs over it.
#   <ENV VAR>|<manifest jq path>|<l1 or l2>
ADDRESS_OVERRIDES=(
  "FEE_DISTRIBUTION_ADDRESS|.l2.contracts.feeDistribution|l2"
  "L1_TOKEN_PORTAL|.l1.contracts.tokenPortal|l1"
  "L1_LIQUIDITY_POOL|.l1.contracts.liquidityPoolProxy|l1"
  "L1_MOCK_DEX_AGGREGATOR|.l1.contracts.mockDexAggregator|l1"
  "L1_TREASURY|.l1.contracts.treasury|l1"
  "L1_COLLATERAL_RESERVE|.l1.contracts.collateralReserve|l1"
  "L1_NETWORK_FUND|.l1.contracts.networkFund|l1"
)
OVERRIDE_LINES=""
for entry in "${ADDRESS_OVERRIDES[@]}"; do
  IFS='|' read -r var path kind <<<"$entry"
  val=$(jq -r "$path // empty" "$MANIFEST")
  if [ "$kind" = l2 ]; then re='^0x[0-9a-fA-F]{64}$'; else re='^0x[0-9a-fA-F]{40}$'; fi
  if ! [[ "$val" =~ $re ]]; then
    echo "FATAL: $path in $MANIFEST is not an $kind address: '${val}' (needed for $var)" >&2
    exit 1
  fi
  OVERRIDE_LINES+="$var=$val"$'\n'
done

REPO=${REPO:-/opt/zeracle}
mkdir -p "$(dirname "$OUT")"
# Written to a temp file and moved, so a failure never leaves a half-written env
# for the next timer run to read. mktemp already creates the file 0600; the
# umask is belt and braces. The trap removes the temp file (key included) if
# any step before the mv fails.
tmp="$(umask 077 && mktemp "$OUT.XXXXXX")"
trap 'rm -f "$tmp"' EXIT
cat > "$tmp" <<EOF
# GENERATED by deployments/pi/gen-keeper-env.sh — do not edit.
# Source: $MANIFEST (generatedAt $(jq -r '.generatedAt // "unknown"' "$MANIFEST"))
KEEPER_L1_PRIVATE_KEY=$KEEPER_KEY_ANVIL_4
V1_L2_DIR=$REPO/v1-l2
ZRCL_ADDRESS=$ZRCL
KEEPER_STATE_DIR=/var/lib/zeracle-keeper
KEEPER_CLAIM_WAIT_SECS=$KEEPER_CLAIM_WAIT_SECS
PENDING_FLUSH_MAX_AGE_SECS=$PENDING_FLUSH_MAX_AGE_SECS
# Addresses pinned from the manifest (ADDRESS_OVERRIDES in gen-keeper-env.sh).
${OVERRIDE_LINES%$'\n'}
EOF
chmod 600 "$tmp"
if [ "$(id -u)" -eq 0 ]; then chown "$OWNER:$OWNER" "$tmp"; fi
mv -f "$tmp" "$OUT"
# Never echo the key.
echo "Wrote $OUT (ZRCL_ADDRESS=$ZRCL)"
